"""
Unit tests for openai_utils.py
"""
import json
import unittest
import pytest
from unittest.mock import patch, MagicMock
import os
from openai_utils import (
    get_openai_client,
    generate_test_data_with_gpt,
    analyze_schema_with_gpt,
    chat_with_gpt_about_schema
)

class TestOpenAIUtils(unittest.TestCase):
    """Test the OpenAI utility functions"""
    
    def setUp(self):
        """Setup test data"""
        # Sample Salesforce schema
        self.account_schema = {
            'name': 'Account',
            'label': 'Account',
            'fields': [
                {
                    'name': 'Name',
                    'label': 'Account Name',
                    'type': 'string',
                    'length': 80,
                    'createable': True,
                    'updateable': True,
                    'nillable': False
                },
                {
                    'name': 'Industry',
                    'label': 'Industry',
                    'type': 'picklist',
                    'createable': True,
                    'updateable': True,
                    'nillable': True,
                    'picklistValues': [
                        {'value': 'Technology', 'active': True},
                        {'value': 'Healthcare', 'active': True},
                        {'value': 'Finance', 'active': True}
                    ]
                },
                {
                    'name': 'AnnualRevenue',
                    'label': 'Annual Revenue',
                    'type': 'currency',
                    'createable': True,
                    'updateable': True,
                    'nillable': True
                }
            ]
        }
        
        # Sample test data that would be generated by GPT
        self.gpt_generated_data = [
            {
                'Name': 'Acme Corporation',
                'Industry': 'Technology',
                'AnnualRevenue': 5000000
            },
            {
                'Name': 'Global Healthcare',
                'Industry': 'Healthcare',
                'AnnualRevenue': 12000000
            },
            {
                'Name': 'City Financial Services',
                'Industry': 'Finance',
                'AnnualRevenue': 8500000
            }
        ]
        
        # Sample schema analysis that would be produced by GPT
        self.gpt_schema_analysis = {
            'objectName': 'Account',
            'description': 'Standard Salesforce Account object for tracking companies.',
            'requiredFields': ['Name'],
            'keyFields': ['Name', 'Industry', 'AnnualRevenue'],
            'fieldTypeBreakdown': {
                'string': 1,
                'picklist': 1,
                'currency': 1
            },
            'relationships': [],
            'bestPractices': [
                'Always provide a unique Account Name',
                'Select an Industry from the picklist values when known',
                'Provide accurate Annual Revenue when available'
            ]
        }
        
        # Sample chat response from GPT
        self.gpt_chat_response = (
            "The Account object represents companies and organizations in Salesforce. "
            "It has three main fields: Name (required text field), Industry (picklist with "
            "values like Technology, Healthcare, and Finance), and AnnualRevenue (currency field). "
            "When creating test data, ensure each Account has a unique name and valid Industry value."
        )

    @patch('openai_utils.OpenAI')
    @patch('openai_utils.os.environ.get')
    def test_get_openai_client(self, mock_environ_get, mock_openai):
        """Test getting an OpenAI client instance"""
        # Setup mocks
        mock_environ_get.return_value = 'test_api_key'
        mock_client = MagicMock()
        mock_openai.return_value = mock_client
        
        # Get client
        client = get_openai_client()
        
        # Verify client was created with API key
        self.assertEqual(client, mock_client)
        mock_openai.assert_called_once_with(api_key='test_api_key')
        
        # Test error handling when API key is missing
        mock_environ_get.return_value = None
        with self.assertRaises(Exception) as context:
            get_openai_client()
        self.assertIn('OPENAI_API_KEY', str(context.exception))

    @patch('openai_utils.get_openai_client')
    def test_generate_test_data_with_gpt(self, mock_get_client):
        """Test generating test data using GPT"""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_message = MagicMock()
        mock_message.content = json.dumps(self.gpt_generated_data)
        mock_response.choices = [MagicMock(message=mock_message)]
        mock_client.chat.completions.create.return_value = mock_response
        mock_get_client.return_value = mock_client
        
        # Generate test data
        records = generate_test_data_with_gpt(self.account_schema, 3)
        
        # Verify result
        self.assertEqual(len(records), 3)
        self.assertEqual(records[0]['Name'], 'Acme Corporation')
        self.assertEqual(records[1]['Industry'], 'Healthcare')
        self.assertEqual(records[2]['AnnualRevenue'], 8500000)
        
        # Verify GPT was called with correct parameters
        mock_client.chat.completions.create.assert_called_once()
        call_kwargs = mock_client.chat.completions.create.call_args[1]
        
        # Should use gpt-4o model
        self.assertEqual(call_kwargs['model'], 'gpt-4o')
        
        # Should include schema in the prompt
        system_content = call_kwargs['messages'][0]['content']
        self.assertIn('generate test data', system_content.lower())
        
        user_content = call_kwargs['messages'][1]['content']
        self.assertIn('Account', user_content)
        self.assertIn('3', user_content)  # Number of records

    @patch('openai_utils.get_openai_client')
    def test_analyze_schema_with_gpt(self, mock_get_client):
        """Test analyzing schema using GPT"""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_message = MagicMock()
        mock_message.content = json.dumps(self.gpt_schema_analysis)
        mock_response.choices = [MagicMock(message=mock_message)]
        mock_client.chat.completions.create.return_value = mock_response
        mock_get_client.return_value = mock_client
        
        # Analyze schema
        analysis = analyze_schema_with_gpt(self.account_schema)
        
        # Verify result
        self.assertEqual(analysis['objectName'], 'Account')
        self.assertIn('Name', analysis['requiredFields'])
        self.assertEqual(len(analysis['keyFields']), 3)
        self.assertEqual(len(analysis['bestPractices']), 3)
        
        # Verify GPT was called with correct parameters
        mock_client.chat.completions.create.assert_called_once()
        call_kwargs = mock_client.chat.completions.create.call_args[1]
        
        # Should use gpt-4o model
        self.assertEqual(call_kwargs['model'], 'gpt-4o')
        
        # Should request JSON output
        system_content = call_kwargs['messages'][0]['content']
        self.assertIn('json format', system_content.lower())
        
        # Should include schema in the prompt
        user_content = call_kwargs['messages'][1]['content']
        self.assertIn('Account', user_content)

    @patch('openai_utils.get_openai_client')
    def test_chat_with_gpt_about_schema(self, mock_get_client):
        """Test interactive chat about a schema using GPT"""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_message = MagicMock()
        mock_message.content = self.gpt_chat_response
        mock_response.choices = [MagicMock(message=mock_message)]
        mock_client.chat.completions.create.return_value = mock_response
        mock_get_client.return_value = mock_client
        
        # Chat about schema
        user_message = "Explain the Account object and its fields."
        response = chat_with_gpt_about_schema(self.account_schema, user_message)
        
        # Verify result
        self.assertEqual(response, self.gpt_chat_response)
        
        # Verify GPT was called with correct parameters
        mock_client.chat.completions.create.assert_called_once()
        call_kwargs = mock_client.chat.completions.create.call_args[1]
        
        # Should use gpt-4o model
        self.assertEqual(call_kwargs['model'], 'gpt-4o')
        
        # Should have both system and user messages
        messages = call_kwargs['messages']
        self.assertEqual(len(messages), 2)
        self.assertEqual(messages[0]['role'], 'system')
        self.assertEqual(messages[1]['role'], 'user')
        
        # System message should include schema context
        system_content = messages[0]['content']
        self.assertIn('Account', system_content)
        
        # User message should be included
        self.assertEqual(messages[1]['content'], user_message)

    @patch('openai_utils.get_openai_client')
    def test_generate_test_data_with_gpt_error(self, mock_get_client):
        """Test error handling when generating test data"""
        # Setup mock to raise exception
        mock_client = MagicMock()
        mock_client.chat.completions.create.side_effect = Exception("API Error")
        mock_get_client.return_value = mock_client
        
        # Attempt to generate test data
        with self.assertRaises(Exception) as context:
            generate_test_data_with_gpt(self.account_schema, 3)
        
        # Verify error is properly handled
        self.assertIn('Error generating test data with GPT', str(context.exception))
        self.assertIn('API Error', str(context.exception))

    @patch('openai_utils.get_openai_client')
    def test_generate_test_data_with_gpt_invalid_response(self, mock_get_client):
        """Test handling invalid GPT responses when generating test data"""
        # Setup mock with invalid JSON response
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_message = MagicMock()
        mock_message.content = "This is not valid JSON"
        mock_response.choices = [MagicMock(message=mock_message)]
        mock_client.chat.completions.create.return_value = mock_response
        mock_get_client.return_value = mock_client
        
        # Attempt to generate test data
        with self.assertRaises(Exception) as context:
            generate_test_data_with_gpt(self.account_schema, 3)
        
        # Verify error is properly handled
        self.assertIn('Error parsing GPT response', str(context.exception))

    @patch('openai_utils.get_openai_client')
    def test_analyze_schema_with_gpt_invalid_response(self, mock_get_client):
        """Test handling invalid GPT responses when analyzing schema"""
        # Setup mock with invalid JSON response
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_message = MagicMock()
        mock_message.content = "This is not valid JSON"
        mock_response.choices = [MagicMock(message=mock_message)]
        mock_client.chat.completions.create.return_value = mock_response
        mock_get_client.return_value = mock_client
        
        # Attempt to analyze schema
        with self.assertRaises(Exception) as context:
            analyze_schema_with_gpt(self.account_schema)
        
        # Verify error is properly handled
        self.assertIn('Error parsing GPT response', str(context.exception))

if __name__ == '__main__':
    unittest.main()